// University of Maryland building list
export const UMD_BUILDINGS = [
  'Mckeldin Library',
  'STAMP Student Union',
  'Hornbake Library',
  'Kim Engineering',
  'E.A Fernandez Idea factory',
  'A.V Williams',
  'A. James Clark Hall',
  'Eppley Recreation Center',
  'IRIBE',
  // Additional common UMD buildings
  'Tydings Hall',
  'Van Munching Hall',
  'Chemistry Building',
  'Biology-Psychology Building',
  'Computer Science Instructional Center',
  'Mathematics Building',
  'Physics Building',
  'Art-Sociology Building',
  'Clarice Smith Performing Arts Center',
  'Ritchie Coliseum',
  'Cole Field House',
  'Xfinity Center',
  'Maryland Stadium',
  'Memorial Chapel',
  'Adele H. Stamp Student Union',
  'Hornbake Library',
  'McKeldin Library',
  'Health Sciences Library',
  'Architecture Building',
  'School of Public Health',
  'School of Public Policy',
  'Robert H. Smith School of Business',
  'A. James Clark School of Engineering',
  'College of Information Studies',
  'Journalism Building',
]


